/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as SitemapDotxmlRouteImport } from './routes/sitemap[.]xml'
import { Route as ServicesRouteImport } from './routes/services'
import { Route as ProjectsRouteImport } from './routes/projects'
import { Route as ContactRouteImport } from './routes/contact'
import { Route as BlogRouteImport } from './routes/blog'
import { Route as AboutRouteImport } from './routes/about'
import { Route as IndexRouteImport } from './routes/index'
import { Route as ServicesIndexRouteImport } from './routes/services.index'
import { Route as ServicesShowerEnclosuresDubaiRouteImport } from './routes/services.shower-enclosures-dubai'
import { Route as ServicesGlassFacadesDubaiRouteImport } from './routes/services.glass-facades-dubai'
import { Route as ServicesFramelessGlassPartitionsDubaiRouteImport } from './routes/services.frameless-glass-partitions-dubai'
import { Route as ServicesCustomMirrorsDubaiRouteImport } from './routes/services.custom-mirrors-dubai'
import { Route as ServicesAluminiumWindowsDubaiRouteImport } from './routes/services.aluminium-windows-dubai'
import { Route as ServicesAluminiumDoorsDubaiRouteImport } from './routes/services.aluminium-doors-dubai'
import { Route as ApiChatRouteImport } from './routes/api/chat'

const SitemapDotxmlRoute = SitemapDotxmlRouteImport.update({
  id: '/sitemap.xml',
  path: '/sitemap.xml',
  getParentRoute: () => rootRouteImport,
} as any)
const ServicesRoute = ServicesRouteImport.update({
  id: '/services',
  path: '/services',
  getParentRoute: () => rootRouteImport,
} as any)
const ProjectsRoute = ProjectsRouteImport.update({
  id: '/projects',
  path: '/projects',
  getParentRoute: () => rootRouteImport,
} as any)
const ContactRoute = ContactRouteImport.update({
  id: '/contact',
  path: '/contact',
  getParentRoute: () => rootRouteImport,
} as any)
const BlogRoute = BlogRouteImport.update({
  id: '/blog',
  path: '/blog',
  getParentRoute: () => rootRouteImport,
} as any)
const AboutRoute = AboutRouteImport.update({
  id: '/about',
  path: '/about',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const ServicesIndexRoute = ServicesIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => ServicesRoute,
} as any)
const ServicesShowerEnclosuresDubaiRoute =
  ServicesShowerEnclosuresDubaiRouteImport.update({
    id: '/shower-enclosures-dubai',
    path: '/shower-enclosures-dubai',
    getParentRoute: () => ServicesRoute,
  } as any)
const ServicesGlassFacadesDubaiRoute =
  ServicesGlassFacadesDubaiRouteImport.update({
    id: '/glass-facades-dubai',
    path: '/glass-facades-dubai',
    getParentRoute: () => ServicesRoute,
  } as any)
const ServicesFramelessGlassPartitionsDubaiRoute =
  ServicesFramelessGlassPartitionsDubaiRouteImport.update({
    id: '/frameless-glass-partitions-dubai',
    path: '/frameless-glass-partitions-dubai',
    getParentRoute: () => ServicesRoute,
  } as any)
const ServicesCustomMirrorsDubaiRoute =
  ServicesCustomMirrorsDubaiRouteImport.update({
    id: '/custom-mirrors-dubai',
    path: '/custom-mirrors-dubai',
    getParentRoute: () => ServicesRoute,
  } as any)
const ServicesAluminiumWindowsDubaiRoute =
  ServicesAluminiumWindowsDubaiRouteImport.update({
    id: '/aluminium-windows-dubai',
    path: '/aluminium-windows-dubai',
    getParentRoute: () => ServicesRoute,
  } as any)
const ServicesAluminiumDoorsDubaiRoute =
  ServicesAluminiumDoorsDubaiRouteImport.update({
    id: '/aluminium-doors-dubai',
    path: '/aluminium-doors-dubai',
    getParentRoute: () => ServicesRoute,
  } as any)
const ApiChatRoute = ApiChatRouteImport.update({
  id: '/api/chat',
  path: '/api/chat',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/blog': typeof BlogRoute
  '/contact': typeof ContactRoute
  '/projects': typeof ProjectsRoute
  '/services': typeof ServicesRouteWithChildren
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/api/chat': typeof ApiChatRoute
  '/services/aluminium-doors-dubai': typeof ServicesAluminiumDoorsDubaiRoute
  '/services/aluminium-windows-dubai': typeof ServicesAluminiumWindowsDubaiRoute
  '/services/custom-mirrors-dubai': typeof ServicesCustomMirrorsDubaiRoute
  '/services/frameless-glass-partitions-dubai': typeof ServicesFramelessGlassPartitionsDubaiRoute
  '/services/glass-facades-dubai': typeof ServicesGlassFacadesDubaiRoute
  '/services/shower-enclosures-dubai': typeof ServicesShowerEnclosuresDubaiRoute
  '/services/': typeof ServicesIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/blog': typeof BlogRoute
  '/contact': typeof ContactRoute
  '/projects': typeof ProjectsRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/api/chat': typeof ApiChatRoute
  '/services/aluminium-doors-dubai': typeof ServicesAluminiumDoorsDubaiRoute
  '/services/aluminium-windows-dubai': typeof ServicesAluminiumWindowsDubaiRoute
  '/services/custom-mirrors-dubai': typeof ServicesCustomMirrorsDubaiRoute
  '/services/frameless-glass-partitions-dubai': typeof ServicesFramelessGlassPartitionsDubaiRoute
  '/services/glass-facades-dubai': typeof ServicesGlassFacadesDubaiRoute
  '/services/shower-enclosures-dubai': typeof ServicesShowerEnclosuresDubaiRoute
  '/services': typeof ServicesIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/blog': typeof BlogRoute
  '/contact': typeof ContactRoute
  '/projects': typeof ProjectsRoute
  '/services': typeof ServicesRouteWithChildren
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/api/chat': typeof ApiChatRoute
  '/services/aluminium-doors-dubai': typeof ServicesAluminiumDoorsDubaiRoute
  '/services/aluminium-windows-dubai': typeof ServicesAluminiumWindowsDubaiRoute
  '/services/custom-mirrors-dubai': typeof ServicesCustomMirrorsDubaiRoute
  '/services/frameless-glass-partitions-dubai': typeof ServicesFramelessGlassPartitionsDubaiRoute
  '/services/glass-facades-dubai': typeof ServicesGlassFacadesDubaiRoute
  '/services/shower-enclosures-dubai': typeof ServicesShowerEnclosuresDubaiRoute
  '/services/': typeof ServicesIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/about'
    | '/blog'
    | '/contact'
    | '/projects'
    | '/services'
    | '/sitemap.xml'
    | '/api/chat'
    | '/services/aluminium-doors-dubai'
    | '/services/aluminium-windows-dubai'
    | '/services/custom-mirrors-dubai'
    | '/services/frameless-glass-partitions-dubai'
    | '/services/glass-facades-dubai'
    | '/services/shower-enclosures-dubai'
    | '/services/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/about'
    | '/blog'
    | '/contact'
    | '/projects'
    | '/sitemap.xml'
    | '/api/chat'
    | '/services/aluminium-doors-dubai'
    | '/services/aluminium-windows-dubai'
    | '/services/custom-mirrors-dubai'
    | '/services/frameless-glass-partitions-dubai'
    | '/services/glass-facades-dubai'
    | '/services/shower-enclosures-dubai'
    | '/services'
  id:
    | '__root__'
    | '/'
    | '/about'
    | '/blog'
    | '/contact'
    | '/projects'
    | '/services'
    | '/sitemap.xml'
    | '/api/chat'
    | '/services/aluminium-doors-dubai'
    | '/services/aluminium-windows-dubai'
    | '/services/custom-mirrors-dubai'
    | '/services/frameless-glass-partitions-dubai'
    | '/services/glass-facades-dubai'
    | '/services/shower-enclosures-dubai'
    | '/services/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AboutRoute: typeof AboutRoute
  BlogRoute: typeof BlogRoute
  ContactRoute: typeof ContactRoute
  ProjectsRoute: typeof ProjectsRoute
  ServicesRoute: typeof ServicesRouteWithChildren
  SitemapDotxmlRoute: typeof SitemapDotxmlRoute
  ApiChatRoute: typeof ApiChatRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/sitemap.xml': {
      id: '/sitemap.xml'
      path: '/sitemap.xml'
      fullPath: '/sitemap.xml'
      preLoaderRoute: typeof SitemapDotxmlRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/services': {
      id: '/services'
      path: '/services'
      fullPath: '/services'
      preLoaderRoute: typeof ServicesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/projects': {
      id: '/projects'
      path: '/projects'
      fullPath: '/projects'
      preLoaderRoute: typeof ProjectsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/contact': {
      id: '/contact'
      path: '/contact'
      fullPath: '/contact'
      preLoaderRoute: typeof ContactRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/blog': {
      id: '/blog'
      path: '/blog'
      fullPath: '/blog'
      preLoaderRoute: typeof BlogRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/about': {
      id: '/about'
      path: '/about'
      fullPath: '/about'
      preLoaderRoute: typeof AboutRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/services/': {
      id: '/services/'
      path: '/'
      fullPath: '/services/'
      preLoaderRoute: typeof ServicesIndexRouteImport
      parentRoute: typeof ServicesRoute
    }
    '/services/shower-enclosures-dubai': {
      id: '/services/shower-enclosures-dubai'
      path: '/shower-enclosures-dubai'
      fullPath: '/services/shower-enclosures-dubai'
      preLoaderRoute: typeof ServicesShowerEnclosuresDubaiRouteImport
      parentRoute: typeof ServicesRoute
    }
    '/services/glass-facades-dubai': {
      id: '/services/glass-facades-dubai'
      path: '/glass-facades-dubai'
      fullPath: '/services/glass-facades-dubai'
      preLoaderRoute: typeof ServicesGlassFacadesDubaiRouteImport
      parentRoute: typeof ServicesRoute
    }
    '/services/frameless-glass-partitions-dubai': {
      id: '/services/frameless-glass-partitions-dubai'
      path: '/frameless-glass-partitions-dubai'
      fullPath: '/services/frameless-glass-partitions-dubai'
      preLoaderRoute: typeof ServicesFramelessGlassPartitionsDubaiRouteImport
      parentRoute: typeof ServicesRoute
    }
    '/services/custom-mirrors-dubai': {
      id: '/services/custom-mirrors-dubai'
      path: '/custom-mirrors-dubai'
      fullPath: '/services/custom-mirrors-dubai'
      preLoaderRoute: typeof ServicesCustomMirrorsDubaiRouteImport
      parentRoute: typeof ServicesRoute
    }
    '/services/aluminium-windows-dubai': {
      id: '/services/aluminium-windows-dubai'
      path: '/aluminium-windows-dubai'
      fullPath: '/services/aluminium-windows-dubai'
      preLoaderRoute: typeof ServicesAluminiumWindowsDubaiRouteImport
      parentRoute: typeof ServicesRoute
    }
    '/services/aluminium-doors-dubai': {
      id: '/services/aluminium-doors-dubai'
      path: '/aluminium-doors-dubai'
      fullPath: '/services/aluminium-doors-dubai'
      preLoaderRoute: typeof ServicesAluminiumDoorsDubaiRouteImport
      parentRoute: typeof ServicesRoute
    }
    '/api/chat': {
      id: '/api/chat'
      path: '/api/chat'
      fullPath: '/api/chat'
      preLoaderRoute: typeof ApiChatRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

interface ServicesRouteChildren {
  ServicesAluminiumDoorsDubaiRoute: typeof ServicesAluminiumDoorsDubaiRoute
  ServicesAluminiumWindowsDubaiRoute: typeof ServicesAluminiumWindowsDubaiRoute
  ServicesCustomMirrorsDubaiRoute: typeof ServicesCustomMirrorsDubaiRoute
  ServicesFramelessGlassPartitionsDubaiRoute: typeof ServicesFramelessGlassPartitionsDubaiRoute
  ServicesGlassFacadesDubaiRoute: typeof ServicesGlassFacadesDubaiRoute
  ServicesShowerEnclosuresDubaiRoute: typeof ServicesShowerEnclosuresDubaiRoute
  ServicesIndexRoute: typeof ServicesIndexRoute
}

const ServicesRouteChildren: ServicesRouteChildren = {
  ServicesAluminiumDoorsDubaiRoute: ServicesAluminiumDoorsDubaiRoute,
  ServicesAluminiumWindowsDubaiRoute: ServicesAluminiumWindowsDubaiRoute,
  ServicesCustomMirrorsDubaiRoute: ServicesCustomMirrorsDubaiRoute,
  ServicesFramelessGlassPartitionsDubaiRoute:
    ServicesFramelessGlassPartitionsDubaiRoute,
  ServicesGlassFacadesDubaiRoute: ServicesGlassFacadesDubaiRoute,
  ServicesShowerEnclosuresDubaiRoute: ServicesShowerEnclosuresDubaiRoute,
  ServicesIndexRoute: ServicesIndexRoute,
}

const ServicesRouteWithChildren = ServicesRoute._addFileChildren(
  ServicesRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AboutRoute: AboutRoute,
  BlogRoute: BlogRoute,
  ContactRoute: ContactRoute,
  ProjectsRoute: ProjectsRoute,
  ServicesRoute: ServicesRouteWithChildren,
  SitemapDotxmlRoute: SitemapDotxmlRoute,
  ApiChatRoute: ApiChatRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
